platform :ios, '13.0'

target 'DetailMoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DetailMoviesApp

 pod 'Alamofire', '~> 5.4.3'
 pod 'AlamofireImage', '~> 4.1'
 pod 'TableviewPaginator'


end